### ISSUE TITLE
[reproducibility] please add either a requirements.txt or environment.yml file

### ISSUE THREAD

**Issue by JeanClaudeR** [lilianmarey/COVID19_Trends_by_Age#5]
Will do this on my fork and I'll submit a PR when ready

**Comment by lilianmarey** [comment]
Alright, thanks a lot

**Comment by JeanClaudeR** [comment]
I will submit a PR on develop branch with an example of environment.yml file as well as a requirements.txt
Note that this requires the use of virtual environment via either conda env (preferred way) or virtualenv.
I'll add a brief note on this

**Comment by JeanClaudeR** [comment]
Created a pull-request for this #7
